language: node_js

node_js: 
  - '10'

services:
  - mongodb

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3 
  - export PATH="$HOME/.yarn/bin:$PATH"

script: yarn test:ci
